col_var = [
    'cluster_life_car_trading_total_count_in_1m', 'cluster_life_car_trading_total_count_out_1m', 'cluster_life_car_trading_qc_count_in_1m', 'cluster_life_car_trading_qc_count_out_1m', 'cluster_life_car_trading_duration_sum_in_1m', 'cluster_life_car_trading_duration_sum_out_1m', 'cluster_life_used_car_trading_total_count_in_1m', 'cluster_life_used_car_trading_total_count_out_1m', 'cluster_life_used_car_trading_qc_count_in_1m', 'cluster_life_used_car_trading_qc_count_out_1m', 'cluster_life_used_car_trading_duration_sum_in_1m', 'cluster_life_used_car_trading_duration_sum_out_1m'
]
